#!/bin/bash
################################################################################
# Fire Department Intranet - Quick Deployment Script
# Repository: https://github.com/thegspiro/fd-intranet
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
APP_DIR="/opt/fd-intranet"
APP_USER="fdapp"
REPO_URL="https://github.com/thegspiro/fd-intranet.git"
DOMAIN=""
DB_PASSWORD=""
SECRET_KEY=""

# Functions
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

get_config() {
    echo "=== Fire Department Intranet Deployment ==="
    echo ""
    
    # Get domain
    read -p "Enter your domain name (e.g., intranet.yourfiredept.org): " DOMAIN
    if [[ -z "$DOMAIN" ]]; then
        print_error "Domain name is required"
        exit 1
    fi
    
    # Generate secret key
    SECRET_KEY=$(python3 -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")
    
    # Get database password
    read -sp "Enter PostgreSQL database password (will be generated if empty): " DB_PASSWORD
    echo ""
    if [[ -z "$DB_PASSWORD" ]]; then
        DB_PASSWORD=$(openssl rand -base64 32)
        print_status "Generated database password: $DB_PASSWORD"
        echo "SAVE THIS PASSWORD!"
        read -p "Press enter to continue..."
    fi
    
    # Get email settings
    read -p "Enter email host (e.g., smtp.gmail.com): " EMAIL_HOST
    read -p "Enter email user (e.g., alerts@yourfiredept.org): " EMAIL_USER
    read -sp "Enter email password/app password: " EMAIL_PASSWORD
    echo ""
}

install_dependencies() {
    print_status "Installing system dependencies..."
    
    apt update
    apt upgrade -y
    apt install -y \
        python3.10 \
        python3.10-venv \
        python3-pip \
        postgresql \
        postgresql-contrib \
        redis-server \
        nginx \
        supervisor \
        git \
        certbot \
        python3-certbot-nginx \
        ufw \
        fail2ban \
        htop \
        vim \
        build-essential \
        libpq-dev \
        python3-dev
    
    print_status "Dependencies installed"
}

setup_firewall() {
    print_status "Configuring firewall..."
    
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow ssh
    ufw allow http
    ufw allow https
    echo "y" | ufw enable
    
    print_status "Firewall configured"
}

create_app_user() {
    print_status "Creating application user..."
    
    if id "$APP_USER" &>/dev/null; then
        print_warning "User $APP_USER already exists"
    else
        adduser --system --group --home $APP_DIR $APP_USER
        print_status "User $APP_USER created"
    fi
    
    mkdir -p $APP_DIR
    chown $APP_USER:$APP_USER $APP_DIR
    chmod 750 $APP_DIR
}

setup_database() {
    print_status "Setting up PostgreSQL database..."
    
    sudo -u postgres psql << EOF
-- Create database
DROP DATABASE IF EXISTS fd_intranet;
CREATE DATABASE fd_intranet;

-- Create user
DROP USER IF EXISTS $APP_USER;
CREATE USER $APP_USER WITH PASSWORD '$DB_PASSWORD';

-- Configure user
ALTER ROLE $APP_USER SET client_encoding TO 'utf8';
ALTER ROLE $APP_USER SET default_transaction_isolation TO 'read committed';
ALTER ROLE $APP_USER SET timezone TO 'UTC';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE fd_intranet TO $APP_USER;

\q
EOF
    
    print_status "Database configured"
}

clone_repository() {
    print_status "Cloning application from GitHub..."
    
    if [ -d "$APP_DIR/app" ]; then
        print_warning "Application directory exists, backing up..."
        mv $APP_DIR/app $APP_DIR/app.backup.$(date +%Y%m%d_%H%M%S)
    fi
    
    sudo -u $APP_USER git clone $REPO_URL $APP_DIR/app
    
    print_status "Repository cloned"
}

setup_python_env() {
    print_status "Setting up Python virtual environment..."
    
    cd $APP_DIR/app
    sudo -u $APP_USER python3.10 -m venv venv
    sudo -u $APP_USER bash -c "source venv/bin/activate && pip install --upgrade pip setuptools wheel"
    sudo -u $APP_USER bash -c "source venv/bin/activate && pip install -r requirements.txt"
    sudo -u $APP_USER bash -c "source venv/bin/activate && pip install gunicorn psycopg2-binary"
    
    print_status "Python environment configured"
}

create_env_file() {
    print_status "Creating environment configuration..."
    
    cat > $APP_DIR/app/.env << EOF
# Generated by deployment script on $(date)

# CRITICAL: SECRET KEY
SECRET_KEY='$SECRET_KEY'

# Environment
DEBUG=False
ALLOWED_HOSTS=$DOMAIN,www.$DOMAIN

# Database
DATABASE_URL=postgresql://$APP_USER:$DB_PASSWORD@localhost:5432/fd_intranet

# Email Configuration
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=$EMAIL_HOST
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=$EMAIL_USER
EMAIL_HOST_PASSWORD=$EMAIL_PASSWORD
DEFAULT_FROM_EMAIL=$EMAIL_USER

# Redis
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# Security Settings
SECURE_SSL_REDIRECT=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True
SECURE_HSTS_SECONDS=31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS=True
SECURE_HSTS_PRELOAD=True

# Geographic Security
GEO_SECURITY_ENABLED=True
TIME_ZONE=America/New_York

# AWS S3 (configure if needed)
USE_S3=False
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=
AWS_S3_REGION_NAME=us-east-1

# Integration APIs (configure as needed)
TARGET_SOLUTIONS_API_KEY=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
MS_CLIENT_ID=
MS_CLIENT_SECRET=
NOCODB_API_TOKEN=
EOF
    
    chown $APP_USER:$APP_USER $APP_DIR/app/.env
    chmod 600 $APP_DIR/app/.env
    
    print_status "Environment file created"
}

run_django_setup() {
    print_status "Running Django setup..."
    
    cd $APP_DIR/app
    
    # Create directories
    sudo -u $APP_USER mkdir -p logs media staticfiles
    
    # Collect static files
    sudo -u $APP_USER bash -c "source venv/bin/activate && python manage.py collectstatic --noinput"
    
    # Run migrations
    sudo -u $APP_USER bash -c "source venv/bin/activate && python manage.py migrate"
    
    # Run setup system
    sudo -u $APP_USER bash -c "source venv/bin/activate && python manage.py setup_system"
    
    print_status "Django setup complete"
    print_warning "You'll need to create a superuser manually later"
}

setup_gunicorn() {
    print_status "Configuring Gunicorn..."
    
    cat > $APP_DIR/app/gunicorn_config.py << 'EOF'
import multiprocessing

bind = "127.0.0.1:8000"
workers = multiprocessing.cpu_count() * 2 + 1
worker_class = 'sync'
timeout = 60
keepalive = 5
accesslog = '/opt/fd-intranet/logs/gunicorn_access.log'
errorlog = '/opt/fd-intranet/logs/gunicorn_error.log'
loglevel = 'info'
proc_name = 'fd-intranet'
user = 'fdapp'
group = 'fdapp'
EOF
    
    chown $APP_USER:$APP_USER $APP_DIR/app/gunicorn_config.py
    
    print_status "Gunicorn configured"
}

setup_supervisor() {
    print_status "Configuring Supervisor..."
    
    cat > /etc/supervisor/conf.d/fd-intranet.conf << EOF
[program:fd-intranet]
command=$APP_DIR/app/venv/bin/gunicorn core.wsgi:application -c $APP_DIR/app/gunicorn_config.py
directory=$APP_DIR/app
user=$APP_USER
group=$APP_USER
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=$APP_DIR/logs/gunicorn_supervisor.log
stderr_logfile=$APP_DIR/logs/gunicorn_supervisor_error.log
environment=PATH="$APP_DIR/app/venv/bin"

[program:fd-intranet-worker]
command=$APP_DIR/app/venv/bin/python manage.py qcluster
directory=$APP_DIR/app
user=$APP_USER
group=$APP_USER
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=$APP_DIR/logs/qcluster.log
stderr_logfile=$APP_DIR/logs/qcluster_error.log
environment=PATH="$APP_DIR/app/venv/bin"
EOF
    
    supervisorctl reread
    supervisorctl update
    supervisorctl start fd-intranet fd-intranet-worker
    
    print_status "Supervisor configured and services started"
}

setup_nginx() {
    print_status "Configuring Nginx..."
    
    cat > /etc/nginx/sites-available/fd-intranet << EOF
upstream fd_intranet {
    server 127.0.0.1:8000 fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    # SSL will be configured by certbot
    
    client_max_body_size 50M;
    
    access_log /var/log/nginx/fd-intranet-access.log;
    error_log /var/log/nginx/fd-intranet-error.log warn;
    
    location /static/ {
        alias $APP_DIR/app/staticfiles/;
        expires 30d;
    }
    
    location /media/ {
        alias $APP_DIR/app/media/;
        expires 7d;
    }
    
    location / {
        proxy_pass http://fd_intranet;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Host \$http_host;
        proxy_redirect off;
    }
}
EOF
    
    ln -sf /etc/nginx/sites-available/fd-intranet /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    
    nginx -t
    systemctl restart nginx
    
    print_status "Nginx configured"
}

setup_ssl() {
    print_status "Setting up SSL certificate..."
    
    mkdir -p /var/www/certbot
    
    certbot --nginx -d $DOMAIN -d www.$DOMAIN --non-interactive --agree-tos --email admin@$DOMAIN
    
    print_status "SSL certificate installed"
}

setup_backups() {
    print_status "Setting up automated backups..."
    
    mkdir -p $APP_DIR/backups
    
    cat > $APP_DIR/backup_db.sh << 'EOF'
#!/bin/bash
BACKUP_DIR="/opt/fd-intranet/backups"
DATE=$(date +%Y%m%d_%H%M%S)
RETENTION_DAYS=30

mkdir -p $BACKUP_DIR

pg_dump -U fdapp -h localhost fd_intranet | \
    gzip > $BACKUP_DIR/fd_intranet_$DATE.sql.gz

find $BACKUP_DIR -name "fd_intranet_*.sql.gz" -mtime +$RETENTION_DAYS -delete

echo "$(date): Database backup completed - fd_intranet_$DATE.sql.gz" >> $BACKUP_DIR/backup.log
EOF
    
    chmod +x $APP_DIR/backup_db.sh
    chown $APP_USER:$APP_USER $APP_DIR/backup_db.sh
    
    # Add to crontab
    (sudo -u $APP_USER crontab -l 2>/dev/null; echo "0 2 * * * $APP_DIR/backup_db.sh") | sudo -u $APP_USER crontab -
    
    print_status "Backup automation configured"
}

print_summary() {
    echo ""
    echo "=========================================="
    echo "Deployment Complete!"
    echo "=========================================="
    echo ""
    echo "Application URL: https://$DOMAIN"
    echo "Database: fd_intranet"
    echo "Database User: $APP_USER"
    echo "Database Password: $DB_PASSWORD"
    echo ""
    echo "IMPORTANT NEXT STEPS:"
    echo "1. Create superuser:"
    echo "   sudo -u $APP_USER bash -c 'cd $APP_DIR/app && source venv/bin/activate && python manage.py createsuperuser'"
    echo ""
    echo "2. Configure user groups in Django admin"
    echo ""
    echo "3. Set up scheduled tasks in Django Q admin"
    echo ""
    echo "4. Test the application: https://$DOMAIN"
    echo ""
    echo "5. Review logs:"
    echo "   sudo tail -f $APP_DIR/logs/gunicorn_error.log"
    echo ""
    echo "Configuration saved to: $APP_DIR/app/.env"
    echo "=========================================="
}

# Main execution
main() {
    echo "=========================================="
    echo "Fire Department Intranet Deployment"
    echo "Repository: https://github.com/thegspiro/fd-intranet"
    echo "=========================================="
    echo ""
    
    check_root
    get_config
    
    echo ""
    echo "Starting deployment..."
    echo ""
    
    install_dependencies
    setup_firewall
    create_app_user
    setup_database
    clone_repository
    setup_python_env
    create_env_file
    run_django_setup
    setup_gunicorn
    setup_supervisor
    setup_nginx
    setup_ssl
    setup_backups
    
    print_summary
}

# Run main function
main
